"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Lists API
  The Twilio SendGrid Marketing Campaigns Lists API allows you to manage your contacts lists programmatically. Lists are static collections of Marketing Campaigns contacts. You can use this API to interact with the list objects themselves. To add contacts to a list, you must use the [Contacts API](https://docs.sendgrid.com/api-reference/contacts/).  You can also manage your lists using the Contacts menu in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/contacts). For more information about lists and best practices for building them, see [**Building your Contact Lists**](https://sendgrid.com/docs/ui/managing-contacts/building-your-contact-list/).
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.mc_lists.v3.models.contact_details import ContactDetails
from sendgrid.rest.api.mc_lists.v3.models.create_marketing_list400_response import (
    CreateMarketingList400Response,
)
from sendgrid.rest.api.mc_lists.v3.models.create_marketing_list_request import (
    CreateMarketingListRequest,
)
from sendgrid.rest.api.mc_lists.v3.models.delete_contact202_response import (
    DeleteContact202Response,
)
from sendgrid.rest.api.mc_lists.v3.models.delete_marketing_list200_response import (
    DeleteMarketingList200Response,
)
from sendgrid.rest.api.mc_lists.v3.models.delete_marketing_list404_response import (
    DeleteMarketingList404Response,
)
from sendgrid.rest.api.mc_lists.v3.models.error import Error
from sendgrid.rest.api.mc_lists.v3.models.get_marketing_list200_response import (
    GetMarketingList200Response,
)
from sendgrid.rest.api.mc_lists.v3.models.list import List
from sendgrid.rest.api.mc_lists.v3.models.list_contact_count200_response import (
    ListContactCount200Response,
)
from sendgrid.rest.api.mc_lists.v3.models.list_marketing_list200_response import (
    ListMarketingList200Response,
)
from sendgrid.rest.api.mc_lists.v3.models.metadata import Metadata
from sendgrid.rest.api.mc_lists.v3.models.self_metadata import SelfMetadata
from sendgrid.rest.api.mc_lists.v3.models.update_marketing_list_request import (
    UpdateMarketingListRequest,
)

__all__ = [
    "ContactDetails",
    "CreateMarketingList400Response",
    "CreateMarketingListRequest",
    "DeleteContact202Response",
    "DeleteMarketingList200Response",
    "DeleteMarketingList404Response",
    "Error",
    "GetMarketingList200Response",
    "List",
    "ListContactCount200Response",
    "ListMarketingList200Response",
    "Metadata",
    "SelfMetadata",
    "UpdateMarketingListRequest",
]
# Testing code
