"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Mail Settings API
  The Twilio SendGrid Mail Settings API allows you to retrieve and configure the various Mail Settings available. Mail Settings instruct SendGrid to apply specific settings to every email that you send over [SendGrid’s Web API](https://docs.sendgrid.com/api-reference/mail-send/v3-mail-send) or [SMTP relay](https://sendgrid.com/docs/for-developers/sending-email/building-an-x-smtpapi-header/). These settings include how to embed a custom footer, how to manage blocks, spam, and bounces, and more.  For a full list of Twilio SendGrid's Mail Settings, and what each one does, see [**Mail Settings**](https://sendgrid.com/docs/ui/account-and-settings/mail/).  You can also manage your Mail Settings in the Twilio SendGrid application user interface.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.mail_settings.v3.models.list_mail_setting200_response import (
    ListMailSetting200Response,
)
from sendgrid.rest.api.mail_settings.v3.models.list_mail_setting200_response_result_inner import (
    ListMailSetting200ResponseResultInner,
)
from sendgrid.rest.api.mail_settings.v3.models.mail_settings_address_whitelabel200 import (
    MailSettingsAddressWhitelabel200,
)
from sendgrid.rest.api.mail_settings.v3.models.mail_settings_bounce_purge import (
    MailSettingsBouncePurge,
)
from sendgrid.rest.api.mail_settings.v3.models.mail_settings_footer import (
    MailSettingsFooter,
)
from sendgrid.rest.api.mail_settings.v3.models.mail_settings_forward_bounce import (
    MailSettingsForwardBounce,
)
from sendgrid.rest.api.mail_settings.v3.models.mail_settings_forward_spam import (
    MailSettingsForwardSpam,
)
from sendgrid.rest.api.mail_settings.v3.models.mail_settings_template200 import (
    MailSettingsTemplate200,
)
from sendgrid.rest.api.mail_settings.v3.models.update_address_whitelist_request import (
    UpdateAddressWhitelistRequest,
)
from sendgrid.rest.api.mail_settings.v3.models.update_template200_response import (
    UpdateTemplate200Response,
)
from sendgrid.rest.api.mail_settings.v3.models.update_template_request import (
    UpdateTemplateRequest,
)

__all__ = [
    "ListMailSetting200Response",
    "ListMailSetting200ResponseResultInner",
    "MailSettingsAddressWhitelabel200",
    "MailSettingsBouncePurge",
    "MailSettingsFooter",
    "MailSettingsForwardBounce",
    "MailSettingsForwardSpam",
    "MailSettingsTemplate200",
    "UpdateAddressWhitelistRequest",
    "UpdateTemplate200Response",
    "UpdateTemplateRequest",
]
# Testing code
