"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Partner API
  The Twilio SendGrid Partner Settings API allows you to integrate your SendGrid account with our partners to increase your SendGrid experience and functionality. For more information about our partners and how you can begin integrating with them, please visit our [Partners page](https://sendgrid.com/partners/marketplace/).
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.partner.v3.models.list_partner_setting200_response import (
    ListPartnerSetting200Response,
)
from sendgrid.rest.api.partner.v3.models.list_partner_setting200_response_result_inner import (
    ListPartnerSetting200ResponseResultInner,
)

__all__ = ["ListPartnerSetting200Response", "ListPartnerSetting200ResponseResultInner"]
# Testing code
