"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Integrations API
  Integrations allows you to connect your SendGrid applications with third-party services and forward SendGrid email events to those external applications. Currently, Integrations supports event forwarding to [Segment](https://segment.com/docs). You can use this API to create, delete, view, and update your Integrations.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.integrations.v3.models.add_integration400_response import (
    AddIntegration400Response,
)
from sendgrid.rest.api.integrations.v3.models.delete_integration400_response import (
    DeleteIntegration400Response,
)
from sendgrid.rest.api.integrations.v3.models.delete_integration404_response import (
    DeleteIntegration404Response,
)
from sendgrid.rest.api.integrations.v3.models.destination import Destination
from sendgrid.rest.api.integrations.v3.models.destination1 import Destination1
from sendgrid.rest.api.integrations.v3.models.destination2 import Destination2
from sendgrid.rest.api.integrations.v3.models.destination3 import Destination3
from sendgrid.rest.api.integrations.v3.models.destination_region import (
    DestinationRegion,
)
from sendgrid.rest.api.integrations.v3.models.destination_region1 import (
    DestinationRegion1,
)
from sendgrid.rest.api.integrations.v3.models.destination_region2 import (
    DestinationRegion2,
)
from sendgrid.rest.api.integrations.v3.models.forbidden import Forbidden
from sendgrid.rest.api.integrations.v3.models.get_integrations_by_user200_response import (
    GetIntegrationsByUser200Response,
)
from sendgrid.rest.api.integrations.v3.models.get_integrations_by_user403_response import (
    GetIntegrationsByUser403Response,
)
from sendgrid.rest.api.integrations.v3.models.get_integrations_by_user500_response import (
    GetIntegrationsByUser500Response,
)
from sendgrid.rest.api.integrations.v3.models.id import Id
from sendgrid.rest.api.integrations.v3.models.integration import Integration
from sendgrid.rest.api.integrations.v3.models.integration_filters import (
    IntegrationFilters,
)
from sendgrid.rest.api.integrations.v3.models.integration_input import IntegrationInput
from sendgrid.rest.api.integrations.v3.models.integration_input_filters import (
    IntegrationInputFilters,
)
from sendgrid.rest.api.integrations.v3.models.integration_input_properties import (
    IntegrationInputProperties,
)
from sendgrid.rest.api.integrations.v3.models.integration_not_found import (
    IntegrationNotFound,
)
from sendgrid.rest.api.integrations.v3.models.integration_patch import IntegrationPatch
from sendgrid.rest.api.integrations.v3.models.integration_patch_filters import (
    IntegrationPatchFilters,
)
from sendgrid.rest.api.integrations.v3.models.integration_patch_properties import (
    IntegrationPatchProperties,
)
from sendgrid.rest.api.integrations.v3.models.integration_properties import (
    IntegrationProperties,
)
from sendgrid.rest.api.integrations.v3.models.internal_error import InternalError
from sendgrid.rest.api.integrations.v3.models.invalid_delete_request import (
    InvalidDeleteRequest,
)
from sendgrid.rest.api.integrations.v3.models.invalid_request import InvalidRequest
from sendgrid.rest.api.integrations.v3.models.items import Items
from sendgrid.rest.api.integrations.v3.models.items1 import Items1
from sendgrid.rest.api.integrations.v3.models.items2 import Items2

__all__ = [
    "AddIntegration400Response",
    "DeleteIntegration400Response",
    "DeleteIntegration404Response",
    "Destination",
    "Destination1",
    "Destination2",
    "Destination3",
    "DestinationRegion",
    "DestinationRegion1",
    "DestinationRegion2",
    "Forbidden",
    "GetIntegrationsByUser200Response",
    "GetIntegrationsByUser403Response",
    "GetIntegrationsByUser500Response",
    "Id",
    "Integration",
    "IntegrationFilters",
    "IntegrationInput",
    "IntegrationInputFilters",
    "IntegrationInputProperties",
    "IntegrationNotFound",
    "IntegrationPatch",
    "IntegrationPatchFilters",
    "IntegrationPatchProperties",
    "IntegrationProperties",
    "InternalError",
    "InvalidDeleteRequest",
    "InvalidRequest",
    "Items",
    "Items1",
    "Items2",
]
# Testing code
