"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Contacts API
  The Twilio SendGrid Marketing Campaigns Contacts API allows you to manage all of your marketing contacts programmatically. You can also import and export contacts using this API. The Contacts API allows you to associate contacts with lists and segments; however, to manage the lists and segments themselves, see the [Lists API](https://docs.sendgrid.com/api-reference/lists/) and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/).  You can also manage your marketing contacts with the [Marketing Campaigns application user interface](https://mc.sendgrid.com/contacts). See [**How to Send Email with New Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/how-to-send-email-with-marketing-campaigns) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.mc_contacts.v3.models.contact_details3 import ContactDetails3
from sendgrid.rest.api.mc_contacts.v3.models.contact_export import ContactExport
from sendgrid.rest.api.mc_contacts.v3.models.contact_import import ContactImport
from sendgrid.rest.api.mc_contacts.v3.models.contact_import_results import (
    ContactImportResults,
)
from sendgrid.rest.api.mc_contacts.v3.models.contact_request import ContactRequest
from sendgrid.rest.api.mc_contacts.v3.models.contact_request_custom_fields import (
    ContactRequestCustomFields,
)
from sendgrid.rest.api.mc_contacts.v3.models.contacts_error import ContactsError
from sendgrid.rest.api.mc_contacts.v3.models.delete_contact202_response import (
    DeleteContact202Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.delete_contact400_response import (
    DeleteContact400Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.delete_contact_identifier202_response import (
    DeleteContactIdentifier202Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.delete_contact_identifier_request import (
    DeleteContactIdentifierRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.mc_contacts.v3.models.error_response_errors_inner import (
    ErrorResponseErrorsInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.export_contact202_response import (
    ExportContact202Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.export_contact_request import (
    ExportContactRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.export_contact_request_notifications import (
    ExportContactRequestNotifications,
)
from sendgrid.rest.api.mc_contacts.v3.models.file_type import FileType
from sendgrid.rest.api.mc_contacts.v3.models.file_type1 import FileType1
from sendgrid.rest.api.mc_contacts.v3.models.get_contact_by_identifiers200_response import (
    GetContactByIdentifiers200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.get_contact_by_identifiers200_response_result_value import (
    GetContactByIdentifiers200ResponseResultValue,
)
from sendgrid.rest.api.mc_contacts.v3.models.get_contact_by_identifiers_request import (
    GetContactByIdentifiersRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.get_import_contact400_response import (
    GetImportContact400Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.identifier_type import IdentifierType
from sendgrid.rest.api.mc_contacts.v3.models.identifier_type1 import IdentifierType1
from sendgrid.rest.api.mc_contacts.v3.models.import_contact200_response import (
    ImportContact200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.import_contact200_response_upload_headers_inner import (
    ImportContact200ResponseUploadHeadersInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.import_contact400_response import (
    ImportContact400Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.import_contact404_response import (
    ImportContact404Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.import_contact_request import (
    ImportContactRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_batched_contact200_response import (
    ListBatchedContact200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_batched_contact_request import (
    ListBatchedContactRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_contact200_response import (
    ListContact200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_contact400_response import (
    ListContact400Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_contact_by_email200_response import (
    ListContactByEmail200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_contact_by_email_request import (
    ListContactByEmailRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_contact_count200_response import (
    ListContactCount200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_contact_count200_response_billable_breakdown import (
    ListContactCount200ResponseBillableBreakdown,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact200_response import (
    ListExportContact200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact200_response_metadata import (
    ListExportContact200ResponseMetadata,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact200_response_result_inner import (
    ListExportContact200ResponseResultInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact200_response_result_inner_metadata import (
    ListExportContact200ResponseResultInnerMetadata,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact200_response_result_inner_segments_inner import (
    ListExportContact200ResponseResultInnerSegmentsInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact400_response import (
    ListExportContact400Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.list_export_contact400_response_errors_inner import (
    ListExportContact400ResponseErrorsInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.metadata import Metadata
from sendgrid.rest.api.mc_contacts.v3.models.search_contact200_response import (
    SearchContact200Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.search_contact400_response import (
    SearchContact400Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.search_contact400_response_errors_inner import (
    SearchContact400ResponseErrorsInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.search_contact500_response import (
    SearchContact500Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.search_contact500_response_errors_inner import (
    SearchContact500ResponseErrorsInner,
)
from sendgrid.rest.api.mc_contacts.v3.models.search_contact_request import (
    SearchContactRequest,
)
from sendgrid.rest.api.mc_contacts.v3.models.self_metadata import SelfMetadata
from sendgrid.rest.api.mc_contacts.v3.models.status import Status
from sendgrid.rest.api.mc_contacts.v3.models.update_contact202_response import (
    UpdateContact202Response,
)
from sendgrid.rest.api.mc_contacts.v3.models.update_contact_request import (
    UpdateContactRequest,
)

__all__ = [
    "ContactDetails3",
    "ContactExport",
    "ContactImport",
    "ContactImportResults",
    "ContactRequest",
    "ContactRequestCustomFields",
    "ContactsError",
    "DeleteContact202Response",
    "DeleteContact400Response",
    "DeleteContactIdentifier202Response",
    "DeleteContactIdentifierRequest",
    "ErrorResponse",
    "ErrorResponseErrorsInner",
    "ExportContact202Response",
    "ExportContactRequest",
    "ExportContactRequestNotifications",
    "FileType",
    "FileType1",
    "GetContactByIdentifiers200Response",
    "GetContactByIdentifiers200ResponseResultValue",
    "GetContactByIdentifiersRequest",
    "GetImportContact400Response",
    "IdentifierType",
    "IdentifierType1",
    "ImportContact200Response",
    "ImportContact200ResponseUploadHeadersInner",
    "ImportContact400Response",
    "ImportContact404Response",
    "ImportContactRequest",
    "ListBatchedContact200Response",
    "ListBatchedContactRequest",
    "ListContact200Response",
    "ListContact400Response",
    "ListContactByEmail200Response",
    "ListContactByEmailRequest",
    "ListContactCount200Response",
    "ListContactCount200ResponseBillableBreakdown",
    "ListExportContact200Response",
    "ListExportContact200ResponseMetadata",
    "ListExportContact200ResponseResultInner",
    "ListExportContact200ResponseResultInnerMetadata",
    "ListExportContact200ResponseResultInnerSegmentsInner",
    "ListExportContact400Response",
    "ListExportContact400ResponseErrorsInner",
    "Metadata",
    "SearchContact200Response",
    "SearchContact400Response",
    "SearchContact400ResponseErrorsInner",
    "SearchContact500Response",
    "SearchContact500ResponseErrorsInner",
    "SearchContactRequest",
    "SelfMetadata",
    "Status",
    "UpdateContact202Response",
    "UpdateContactRequest",
]
# Testing code
