"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Designs
  The Twilio SendGrid Designs API offers the ability to manage assets stored in the Twilio SendGrid [Design Library](https://mc.sendgrid.com/design-library/my-designs).  The Design Library is a feature-rich email layout tool and media repository. You can [build designs for all your marketing email needs](https://sendgrid.com/docs/ui/sending-email/working-with-marketing-campaigns-email-designs/), including Single Sends and Automations.  You can also duplicate and then modify one of the pre-built designs provided by Twilio SendGrid to get you started.  The Designs API provides a REST-like interface for creating new designs, retrieving a list of existing designs, duplicating or updating a design, and deleting a design.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.mc_designs.v3.models.api_error import ApiError
from sendgrid.rest.api.mc_designs.v3.models.api_errors import ApiErrors
from sendgrid.rest.api.mc_designs.v3.models.design_common_properties import (
    DesignCommonProperties,
)
from sendgrid.rest.api.mc_designs.v3.models.design_duplicate_input import (
    DesignDuplicateInput,
)
from sendgrid.rest.api.mc_designs.v3.models.design_input import DesignInput
from sendgrid.rest.api.mc_designs.v3.models.design_output import DesignOutput
from sendgrid.rest.api.mc_designs.v3.models.design_output_summary import (
    DesignOutputSummary,
)
from sendgrid.rest.api.mc_designs.v3.models.editor import Editor
from sendgrid.rest.api.mc_designs.v3.models.list_design200_response import (
    ListDesign200Response,
)
from sendgrid.rest.api.mc_designs.v3.models.metadata import Metadata
from sendgrid.rest.api.mc_designs.v3.models.update_design_request import (
    UpdateDesignRequest,
)

__all__ = [
    "ApiError",
    "ApiErrors",
    "DesignCommonProperties",
    "DesignDuplicateInput",
    "DesignInput",
    "DesignOutput",
    "DesignOutputSummary",
    "Editor",
    "ListDesign200Response",
    "Metadata",
    "UpdateDesignRequest",
]
# Testing code
