"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Send Test Email API
  The Twilio SendGrid Test Email API allows you to test a marketing email by first sending it to a list of up to 10 email addresses before pushing to a contact list or segment. With this feature, you can test the layout and content of your message in multiple email clients and with multiple recipients to see how it will function in a real-world scenario.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.mc_test.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.mc_test.v3.models.error_response_errors_inner import (
    ErrorResponseErrorsInner,
)
from sendgrid.rest.api.mc_test.v3.models.send_test_marketing_email_request import (
    SendTestMarketingEmailRequest,
)

__all__ = ["ErrorResponse", "ErrorResponseErrorsInner", "SendTestMarketingEmailRequest"]
# Testing code
