"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Tracking Settings API
  The Twilio SendGrid Tracking Settings API allows you to configure which tracking settings are enabled for your messages. You can track many of your recipients' interactions with your emails, including which emails they open, which links they click, and when they subscribe to or unsubscribe from your emails. See [**Tracking Settings**](https://docs.sendgrid.com/ui/account-and-settings/tracking) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.tracking_settings.v3.models.click_tracking import ClickTracking
from sendgrid.rest.api.tracking_settings.v3.models.google_analytics_settings import (
    GoogleAnalyticsSettings,
)
from sendgrid.rest.api.tracking_settings.v3.models.list_open_tracking_setting200_response import (
    ListOpenTrackingSetting200Response,
)
from sendgrid.rest.api.tracking_settings.v3.models.list_tracking_setting200_response import (
    ListTrackingSetting200Response,
)
from sendgrid.rest.api.tracking_settings.v3.models.list_tracking_setting200_response_result_inner import (
    ListTrackingSetting200ResponseResultInner,
)
from sendgrid.rest.api.tracking_settings.v3.models.subscription_tracking_settings import (
    SubscriptionTrackingSettings,
)
from sendgrid.rest.api.tracking_settings.v3.models.update_click_tracking_setting_request import (
    UpdateClickTrackingSettingRequest,
)
from sendgrid.rest.api.tracking_settings.v3.models.update_open_tracking_setting_request import (
    UpdateOpenTrackingSettingRequest,
)

__all__ = [
    "ClickTracking",
    "GoogleAnalyticsSettings",
    "ListOpenTrackingSetting200Response",
    "ListTrackingSetting200Response",
    "ListTrackingSetting200ResponseResultInner",
    "SubscriptionTrackingSettings",
    "UpdateClickTrackingSettingRequest",
    "UpdateOpenTrackingSettingRequest",
]
# Testing code
