"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Scopes API
  The Twilio SendGrid Scopes API allows you to retrieve the scopes or permissions available to a user, see the user's attempts to access your SendGrid account, and, if necessary, deny an access request.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.scopes.v3.models.approve_scope_request200_response import ApproveScopeRequest200Response
from sendgrid.rest.api.scopes.v3.models.deny_scope_request404_response import DenyScopeRequest404Response
from sendgrid.rest.api.scopes.v3.models.deny_scope_request404_response_errors_inner import DenyScopeRequest404ResponseErrorsInner
from sendgrid.rest.api.scopes.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.scopes.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.scopes.v3.models.list_scope200_response import ListScope200Response
from sendgrid.rest.api.scopes.v3.models.list_scope401_response import ListScope401Response
from sendgrid.rest.api.scopes.v3.models.list_scope401_response_errors_inner import ListScope401ResponseErrorsInner
from sendgrid.rest.api.scopes.v3.models.list_scope_request200_response_inner import ListScopeRequest200ResponseInner
__all__ = [ 'ApproveScopeRequest200Response',   'DenyScopeRequest404Response',   'DenyScopeRequest404ResponseErrorsInner',   'ErrorResponse',   'ErrorResponseErrorsInner',   'ListScope200Response',   'ListScope401Response',   'ListScope401ResponseErrorsInner',   'ListScopeRequest200ResponseInner'  ]
# Testing code