"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Teammates API
  The Twilio SendGrid Teammates API allows you to add, manage, and remove Teammates, or user accounts, from your SendGrid account. Teammates function like user accounts on the SendGrid account, allowing you to invite additional users to your account with scoped access. You can think of Teammates as SendGrid's approach to enabling [role-based access control](https://en.wikipedia.org/wiki/Role-based_access_control) for your SendGrid account. For even more control over the access to your account, see the [Twilio SendGrid SSO API](https://docs.sendgrid.com/api-reference/single-sign-on-teammates/), which enables SSO-authenticated Teammates to be managed through a SAML 2.0 identity provider.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.teammates.v3.models.get_teammate200_response import GetTeammate200Response
from sendgrid.rest.api.teammates.v3.models.invite_teammate201_response import InviteTeammate201Response
from sendgrid.rest.api.teammates.v3.models.invite_teammate400_response import InviteTeammate400Response
from sendgrid.rest.api.teammates.v3.models.invite_teammate400_response_errors_inner import InviteTeammate400ResponseErrorsInner
from sendgrid.rest.api.teammates.v3.models.invite_teammate_request import InviteTeammateRequest
from sendgrid.rest.api.teammates.v3.models.list_pending_teammate200_response import ListPendingTeammate200Response
from sendgrid.rest.api.teammates.v3.models.list_pending_teammate200_response_result_inner import ListPendingTeammate200ResponseResultInner
from sendgrid.rest.api.teammates.v3.models.list_subuser_by_template200_response import ListSubuserByTemplate200Response
from sendgrid.rest.api.teammates.v3.models.list_subuser_by_template200_response_metadata import ListSubuserByTemplate200ResponseMetadata
from sendgrid.rest.api.teammates.v3.models.list_subuser_by_template200_response_metadata_next_params import ListSubuserByTemplate200ResponseMetadataNextParams
from sendgrid.rest.api.teammates.v3.models.list_subuser_by_template200_response_subuser_access_inner import ListSubuserByTemplate200ResponseSubuserAccessInner
from sendgrid.rest.api.teammates.v3.models.list_subuser_by_template400_response import ListSubuserByTemplate400Response
from sendgrid.rest.api.teammates.v3.models.list_subuser_by_template400_response_errors_inner import ListSubuserByTemplate400ResponseErrorsInner
from sendgrid.rest.api.teammates.v3.models.list_teammate200_response import ListTeammate200Response
from sendgrid.rest.api.teammates.v3.models.list_teammate200_response_result_inner import ListTeammate200ResponseResultInner
from sendgrid.rest.api.teammates.v3.models.permission_type import PermissionType
from sendgrid.rest.api.teammates.v3.models.resend_teammate_invite200_response import ResendTeammateInvite200Response
from sendgrid.rest.api.teammates.v3.models.update_teammate200_response import UpdateTeammate200Response
from sendgrid.rest.api.teammates.v3.models.update_teammate_request import UpdateTeammateRequest
from sendgrid.rest.api.teammates.v3.models.user_type import UserType
from sendgrid.rest.api.teammates.v3.models.user_type1 import UserType1
from sendgrid.rest.api.teammates.v3.models.user_type2 import UserType2
__all__ = [ 'GetTeammate200Response',   'InviteTeammate201Response',   'InviteTeammate400Response',   'InviteTeammate400ResponseErrorsInner',   'InviteTeammateRequest',   'ListPendingTeammate200Response',   'ListPendingTeammate200ResponseResultInner',   'ListSubuserByTemplate200Response',   'ListSubuserByTemplate200ResponseMetadata',   'ListSubuserByTemplate200ResponseMetadataNextParams',   'ListSubuserByTemplate200ResponseSubuserAccessInner',   'ListSubuserByTemplate400Response',   'ListSubuserByTemplate400ResponseErrorsInner',   'ListTeammate200Response',   'ListTeammate200ResponseResultInner',   'PermissionType',   'ResendTeammateInvite200Response',   'UpdateTeammate200Response',   'UpdateTeammateRequest',   'UserType',   'UserType1',   'UserType2'  ]
# Testing code