version: "3.3"

services:
  sendgrid:
   image: sendgrid/sendgrid-python:${TAG}
   restart: unless-stopped
   container_name: sendgrid-prod
   tty: true
   env_file:
     - .env

  sendgrid-dev:
    build:
      context: .
      args:
        - SENDGRID-PYTHON_VERSION=${SENDGRID_PYTHON_VERSION}
        - HTTP-CLIENT_VERSION=${HTTP_CLIENT_VERSION}
    restart: unless-stopped
    container_name: sendgrid-dev
    tty: true
    env_file:
      - .env
    volumes:
      -  ${PATH_TO_SENDGRID_PYTHON_DEV}:/mnt/sendgrid-python
      -  ${PATH_TO_HTTP_CLIENT_DEV}:/mnt/python-http-client

  sendgrid-beta:
   image: sendgrid/sendgrid-python:${TAG}
   restart: unless-stopped
   container_name: sendgrid-beta
   tty: true
   env_file:
     - .env
   volumes:
     -  ${PATH_TO_SENDGRID_PYTHON_FORK}:/root/sources/sendgrid-python/sendgrid
