"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Legacy Marketing Campaigns Sender Identities API
  The Twilio SendGrid Legacy Marketing Campaigns Sender Identites API allows you to manage the email addresses used to send your marketing email. This API is operational, but we recommend using the current version of Marketing Campaigns to manage your [senders](https://docs.sendgrid.com/api-reference/senders/).  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.lmc_senders.v3.models.create_sender400_response import CreateSender400Response
from sendgrid.rest.api.lmc_senders.v3.models.create_sender400_response_errors_inner import CreateSender400ResponseErrorsInner
from sendgrid.rest.api.lmc_senders.v3.models.create_sender_request import CreateSenderRequest
from sendgrid.rest.api.lmc_senders.v3.models.list_sender200_response import ListSender200Response
from sendgrid.rest.api.lmc_senders.v3.models.sender_id import SenderId
from sendgrid.rest.api.lmc_senders.v3.models.sender_id_request import SenderIdRequest
from sendgrid.rest.api.lmc_senders.v3.models.sender_id_request_from import SenderIdRequestFrom
from sendgrid.rest.api.lmc_senders.v3.models.sender_id_request_reply_to import SenderIdRequestReplyTo
__all__ = [ 'CreateSender400Response',   'CreateSender400ResponseErrorsInner',   'CreateSenderRequest',   'ListSender200Response',   'SenderId',   'SenderIdRequest',   'SenderIdRequestFrom',   'SenderIdRequestReplyTo'  ]
# Testing code