"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Legacy Marketing Campaigns Campaigns API
  The Twilio SendGrid Legacy Marketing Campaigns Campaigns API allows you to manage your marketing email messages programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns to manage your marketing messages with SendGrid [Single Sends](https://docs.sendgrid.com/api-reference/single-sends/) and [Automations](https://docs.sendgrid.com/ui/sending-email/getting-started-with-automation).  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.lmc_campaigns.v3.models.campaigns2xx import Campaigns2xx
from sendgrid.rest.api.lmc_campaigns.v3.models.editor import Editor
from sendgrid.rest.api.lmc_campaigns.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.lmc_campaigns.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.lmc_campaigns.v3.models.get_campaign200_response import GetCampaign200Response
from sendgrid.rest.api.lmc_campaigns.v3.models.list_campaign200_response import ListCampaign200Response
from sendgrid.rest.api.lmc_campaigns.v3.models.post_campaigns_request import PostCampaignsRequest
from sendgrid.rest.api.lmc_campaigns.v3.models.schedule_a_campaign_request import ScheduleACampaignRequest
from sendgrid.rest.api.lmc_campaigns.v3.models.schedule_a_campaign_response import ScheduleACampaignResponse
from sendgrid.rest.api.lmc_campaigns.v3.models.send_a_campaign_response import SendACampaignResponse
from sendgrid.rest.api.lmc_campaigns.v3.models.send_a_test_campaign_request import SendATestCampaignRequest
from sendgrid.rest.api.lmc_campaigns.v3.models.send_test_campaign_request import SendTestCampaignRequest
from sendgrid.rest.api.lmc_campaigns.v3.models.status import Status
from sendgrid.rest.api.lmc_campaigns.v3.models.update_a_campaign_request import UpdateACampaignRequest
from sendgrid.rest.api.lmc_campaigns.v3.models.update_a_scheduled_campaign_request import UpdateAScheduledCampaignRequest
from sendgrid.rest.api.lmc_campaigns.v3.models.update_a_scheduled_campaign_response import UpdateAScheduledCampaignResponse
from sendgrid.rest.api.lmc_campaigns.v3.models.view_scheduled_time_of_a_campaign_response import ViewScheduledTimeOfACampaignResponse
__all__ = [ 'Campaigns2xx',   'Editor',   'ErrorResponse',   'ErrorResponseErrorsInner',   'GetCampaign200Response',   'ListCampaign200Response',   'PostCampaignsRequest',   'ScheduleACampaignRequest',   'ScheduleACampaignResponse',   'SendACampaignResponse',   'SendATestCampaignRequest',   'SendTestCampaignRequest',   'Status',   'UpdateACampaignRequest',   'UpdateAScheduledCampaignRequest',   'UpdateAScheduledCampaignResponse',   'ViewScheduledTimeOfACampaignResponse'  ]
# Testing code