"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Mail API
  The Twilio SendGrid v3 Mail API allows you to send email at scale over HTTP. The Mail Send endpoint supports many levels of functionality, allowing you to send templates, set categories and custom arguments that can be used to analyze your send, and configure which tracking settings to include such as opens and clicks. You can also group mail sends into batches, allowing you to schedule and cancel sends by their batch IDs.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.mail.v3.models.content_encoding import ContentEncoding
from sendgrid.rest.api.mail.v3.models.disposition import Disposition
from sendgrid.rest.api.mail.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.mail.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.mail.v3.models.mail_batch_response import MailBatchResponse
from sendgrid.rest.api.mail.v3.models.mail_from import MailFrom
from sendgrid.rest.api.mail.v3.models.mail_to import MailTo
from sendgrid.rest.api.mail.v3.models.send_mail_request import SendMailRequest
from sendgrid.rest.api.mail.v3.models.send_mail_request_asm import SendMailRequestAsm
from sendgrid.rest.api.mail.v3.models.send_mail_request_attachments_inner import SendMailRequestAttachmentsInner
from sendgrid.rest.api.mail.v3.models.send_mail_request_content_inner import SendMailRequestContentInner
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings import SendMailRequestMailSettings
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings_bypass_bounce_management import SendMailRequestMailSettingsBypassBounceManagement
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings_bypass_list_management import SendMailRequestMailSettingsBypassListManagement
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings_bypass_spam_management import SendMailRequestMailSettingsBypassSpamManagement
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings_bypass_unsubscribe_management import SendMailRequestMailSettingsBypassUnsubscribeManagement
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings_footer import SendMailRequestMailSettingsFooter
from sendgrid.rest.api.mail.v3.models.send_mail_request_mail_settings_sandbox_mode import SendMailRequestMailSettingsSandboxMode
from sendgrid.rest.api.mail.v3.models.send_mail_request_personalizations_inner import SendMailRequestPersonalizationsInner
from sendgrid.rest.api.mail.v3.models.send_mail_request_tracking_settings import SendMailRequestTrackingSettings
from sendgrid.rest.api.mail.v3.models.send_mail_request_tracking_settings_click_tracking import SendMailRequestTrackingSettingsClickTracking
from sendgrid.rest.api.mail.v3.models.send_mail_request_tracking_settings_ganalytics import SendMailRequestTrackingSettingsGanalytics
from sendgrid.rest.api.mail.v3.models.send_mail_request_tracking_settings_open_tracking import SendMailRequestTrackingSettingsOpenTracking
from sendgrid.rest.api.mail.v3.models.send_mail_request_tracking_settings_subscription_tracking import SendMailRequestTrackingSettingsSubscriptionTracking
__all__ = [ 'ContentEncoding',   'Disposition',   'ErrorResponse',   'ErrorResponseErrorsInner',   'MailBatchResponse',   'MailFrom',   'MailTo',   'SendMailRequest',   'SendMailRequestAsm',   'SendMailRequestAttachmentsInner',   'SendMailRequestContentInner',   'SendMailRequestMailSettings',   'SendMailRequestMailSettingsBypassBounceManagement',   'SendMailRequestMailSettingsBypassListManagement',   'SendMailRequestMailSettingsBypassSpamManagement',   'SendMailRequestMailSettingsBypassUnsubscribeManagement',   'SendMailRequestMailSettingsFooter',   'SendMailRequestMailSettingsSandboxMode',   'SendMailRequestPersonalizationsInner',   'SendMailRequestTrackingSettings',   'SendMailRequestTrackingSettingsClickTracking',   'SendMailRequestTrackingSettingsGanalytics',   'SendMailRequestTrackingSettingsOpenTracking',   'SendMailRequestTrackingSettingsSubscriptionTracking'  ]
# Testing code