"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Statistics API
  The Marketing Campaigns Stats API allows you to retrieve statistics for both Automations and Single Sends. The statistics provided include bounces, clicks, opens, and more. You can export stats in CSV format for use in other applications. You can also retrieve Marketing Campaigns stats in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/).  This API provides statistics for Marketing Campaigns only. For stats related to event tracking, please see the [Stats API](https://docs.sendgrid.com/api-reference/stats).
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.mc_stats.v3.models.ab_phase import AbPhase
from sendgrid.rest.api.mc_stats.v3.models.ab_phase1 import AbPhase1
from sendgrid.rest.api.mc_stats.v3.models.ab_phase_id import AbPhaseId
from sendgrid.rest.api.mc_stats.v3.models.aggregated_by import AggregatedBy
from sendgrid.rest.api.mc_stats.v3.models.autmoations_link_stats_response import AutmoationsLinkStatsResponse
from sendgrid.rest.api.mc_stats.v3.models.autmoations_link_stats_response_results_inner import AutmoationsLinkStatsResponseResultsInner
from sendgrid.rest.api.mc_stats.v3.models.automations_response import AutomationsResponse
from sendgrid.rest.api.mc_stats.v3.models.automations_response_results_inner import AutomationsResponseResultsInner
from sendgrid.rest.api.mc_stats.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.mc_stats.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.mc_stats.v3.models.items import Items
from sendgrid.rest.api.mc_stats.v3.models.items1 import Items1
from sendgrid.rest.api.mc_stats.v3.models.items2 import Items2
from sendgrid.rest.api.mc_stats.v3.models.link_tracking_metadata import LinkTrackingMetadata
from sendgrid.rest.api.mc_stats.v3.models.metadata import Metadata
from sendgrid.rest.api.mc_stats.v3.models.metrics import Metrics
from sendgrid.rest.api.mc_stats.v3.models.singlesends_link_stats_response import SinglesendsLinkStatsResponse
from sendgrid.rest.api.mc_stats.v3.models.singlesends_link_stats_response_results_inner import SinglesendsLinkStatsResponseResultsInner
from sendgrid.rest.api.mc_stats.v3.models.singlesends_response import SinglesendsResponse
from sendgrid.rest.api.mc_stats.v3.models.singlesends_response_results_inner import SinglesendsResponseResultsInner
__all__ = [ 'AbPhase',   'AbPhase1',   'AbPhaseId',   'AggregatedBy',   'AutmoationsLinkStatsResponse',   'AutmoationsLinkStatsResponseResultsInner',   'AutomationsResponse',   'AutomationsResponseResultsInner',   'ErrorResponse',   'ErrorResponseErrorsInner',   'Items',   'Items1',   'Items2',   'LinkTrackingMetadata',   'Metadata',   'Metrics',   'SinglesendsLinkStatsResponse',   'SinglesendsLinkStatsResponseResultsInner',   'SinglesendsResponse',   'SinglesendsResponseResultsInner'  ]
# Testing code