"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Enforced TLS API
  The Twilio SendGrid Enforced TLS API allows you to specify whether or not the recipient of your mail send is required to support TLS or have a valid certificate.  Twilio SendGrid sends all emails with [Opportunistic TLS](https://sendgrid.com/blog/myth-opportunistic-tls-email-privacy/) by default, meaning email is sent with TLS, and if the recipient's inbox provider does not accept the TLS encryption, we then send the message unencrypted.  You can optionally choose to enforce TLS encryption, meaning that if the recipient's inbox provider does not accept the TLS encryption, Twilio SendGrid drops the message and sends a block event with the message, “TLS required but not supported” as the description.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.enforced_tls.v3.models.enforced_tls_request_response import EnforcedTlsRequestResponse
from sendgrid.rest.api.enforced_tls.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.enforced_tls.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.enforced_tls.v3.models.version import Version
__all__ = [ 'EnforcedTlsRequestResponse',   'ErrorResponse',   'ErrorResponseErrorsInner',   'Version'  ]
# Testing code