"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Legacy Marketing Campaigns Contacts API
  The Twilio SendGrid Legacy Marketing Campaigns Contacts API allows you to manage your marketing contacts programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns' [Contacts API](https://docs.sendgrid.com/api-reference/contacts/), [Lists API](https://docs.sendgrid.com/api-reference/lists/), and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) to manage your contacts.  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.lmc_contactdb.v3.models.add_recipient_request_inner import AddRecipientRequestInner
from sendgrid.rest.api.lmc_contactdb.v3.models.and_or import AndOr
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_custom_field import ContactdbCustomField
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_custom_field_id2xx import ContactdbCustomFieldId2xx
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_custom_field_id_value import ContactdbCustomFieldIdValue
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_list2xx import ContactdbList2xx
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_recipient200 import ContactdbRecipient200
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_recipient200_recipients_inner import ContactdbRecipient200RecipientsInner
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_recipient_count200 import ContactdbRecipientCount200
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_recipient_response201 import ContactdbRecipientResponse201
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_recipient_response201_errors_inner import ContactdbRecipientResponse201ErrorsInner
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_segments import ContactdbSegments
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_segments_conditions import ContactdbSegmentsConditions
from sendgrid.rest.api.lmc_contactdb.v3.models.contactdb_segments_id200 import ContactdbSegmentsId200
from sendgrid.rest.api.lmc_contactdb.v3.models.create_a_list_request import CreateAListRequest
from sendgrid.rest.api.lmc_contactdb.v3.models.create_custom_field_request import CreateCustomFieldRequest
from sendgrid.rest.api.lmc_contactdb.v3.models.delete_contacts import DeleteContacts
from sendgrid.rest.api.lmc_contactdb.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.lmc_contactdb.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.lmc_contactdb.v3.models.get_recipient_list200_response import GetRecipientList200Response
from sendgrid.rest.api.lmc_contactdb.v3.models.list_all_custom_fields_response import ListAllCustomFieldsResponse
from sendgrid.rest.api.lmc_contactdb.v3.models.list_all_lists_response import ListAllListsResponse
from sendgrid.rest.api.lmc_contactdb.v3.models.list_all_segments_response import ListAllSegmentsResponse
from sendgrid.rest.api.lmc_contactdb.v3.models.list_recipients_from_contact_db_list200_response import ListRecipientsFromContactDbList200Response
from sendgrid.rest.api.lmc_contactdb.v3.models.list_recipients_on_a_segment_response import ListRecipientsOnASegmentResponse
from sendgrid.rest.api.lmc_contactdb.v3.models.list_recipients_response import ListRecipientsResponse
from sendgrid.rest.api.lmc_contactdb.v3.models.list_reserved_field200_response import ListReservedField200Response
from sendgrid.rest.api.lmc_contactdb.v3.models.list_reserved_field200_response_reserved_fields_inner import ListReservedField200ResponseReservedFieldsInner
from sendgrid.rest.api.lmc_contactdb.v3.models.list_status200_response import ListStatus200Response
from sendgrid.rest.api.lmc_contactdb.v3.models.list_status200_response_status_inner import ListStatus200ResponseStatusInner
from sendgrid.rest.api.lmc_contactdb.v3.models.operator import Operator
from sendgrid.rest.api.lmc_contactdb.v3.models.search_recipient200_response import SearchRecipient200Response
from sendgrid.rest.api.lmc_contactdb.v3.models.search_recipient200_response_recipients_inner import SearchRecipient200ResponseRecipientsInner
from sendgrid.rest.api.lmc_contactdb.v3.models.search_recipient200_response_recipients_inner_custom_fields_inner import SearchRecipient200ResponseRecipientsInnerCustomFieldsInner
from sendgrid.rest.api.lmc_contactdb.v3.models.search_recipient200_response_recipients_inner_custom_fields_inner_value import SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue
from sendgrid.rest.api.lmc_contactdb.v3.models.search_recipient_request import SearchRecipientRequest
from sendgrid.rest.api.lmc_contactdb.v3.models.type import Type
from sendgrid.rest.api.lmc_contactdb.v3.models.update_a_list_request import UpdateAListRequest
from sendgrid.rest.api.lmc_contactdb.v3.models.update_contact_db_list200_response import UpdateContactDbList200Response
from sendgrid.rest.api.lmc_contactdb.v3.models.update_recipient_request_inner import UpdateRecipientRequestInner
from sendgrid.rest.api.lmc_contactdb.v3.models.update_segment_request import UpdateSegmentRequest
__all__ = [ 'AddRecipientRequestInner',   'AndOr',   'ContactdbCustomField',   'ContactdbCustomFieldId2xx',   'ContactdbCustomFieldIdValue',   'ContactdbList2xx',   'ContactdbRecipient200',   'ContactdbRecipient200RecipientsInner',   'ContactdbRecipientCount200',   'ContactdbRecipientResponse201',   'ContactdbRecipientResponse201ErrorsInner',   'ContactdbSegments',   'ContactdbSegmentsConditions',   'ContactdbSegmentsId200',   'CreateAListRequest',   'CreateCustomFieldRequest',   'DeleteContacts',   'ErrorResponse',   'ErrorResponseErrorsInner',   'GetRecipientList200Response',   'ListAllCustomFieldsResponse',   'ListAllListsResponse',   'ListAllSegmentsResponse',   'ListRecipientsFromContactDbList200Response',   'ListRecipientsOnASegmentResponse',   'ListRecipientsResponse',   'ListReservedField200Response',   'ListReservedField200ResponseReservedFieldsInner',   'ListStatus200Response',   'ListStatus200ResponseStatusInner',   'Operator',   'SearchRecipient200Response',   'SearchRecipient200ResponseRecipientsInner',   'SearchRecipient200ResponseRecipientsInnerCustomFieldsInner',   'SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue',   'SearchRecipientRequest',   'Type',   'UpdateAListRequest',   'UpdateContactDbList200Response',   'UpdateRecipientRequestInner',   'UpdateSegmentRequest'  ]
# Testing code