"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Segments API
  This API was deprecated on December 31, 2022. Following deprecation, all segments created in the Marketing Campaigns user interface began using the [Segmentation v2 API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2).  To enable manual migration and data retrieval, this API's GET and DELETE operations will remain available. The POST (create) and PATCH (update) endpoints were removed on January 31, 2023 because it is no longer possible to create new v1 segments or modify existing ones. See our [Segmentation v1 to v2 upgrade instructions](https://docs.sendgrid.com/for-developers/sending-email/getting-started-the-marketing-campaigns-v2-segmentation-api#upgrade-a-v1-segment-to-v2) to manually migrate your segments to the v2 API.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.mc_segments.v3.models.contact_response import ContactResponse
from sendgrid.rest.api.mc_segments.v3.models.contact_response_custom_fields import ContactResponseCustomFields
from sendgrid.rest.api.mc_segments.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.mc_segments.v3.models.error_response_errors_inner import ErrorResponseErrorsInner
from sendgrid.rest.api.mc_segments.v3.models.full_segment import FullSegment
from sendgrid.rest.api.mc_segments.v3.models.get_segment404_response import GetSegment404Response
from sendgrid.rest.api.mc_segments.v3.models.get_segment404_response_errors_inner import GetSegment404ResponseErrorsInner
from sendgrid.rest.api.mc_segments.v3.models.list_segment200_response import ListSegment200Response
from sendgrid.rest.api.mc_segments.v3.models.list_segment500_response import ListSegment500Response
from sendgrid.rest.api.mc_segments.v3.models.list_segment500_response_errors_inner import ListSegment500ResponseErrorsInner
from sendgrid.rest.api.mc_segments.v3.models.segment_summary import SegmentSummary
from sendgrid.rest.api.mc_segments.v3.models.segment_write_v2 import SegmentWriteV2
__all__ = [ 'ContactResponse',   'ContactResponseCustomFields',   'ErrorResponse',   'ErrorResponseErrorsInner',   'FullSegment',   'GetSegment404Response',   'GetSegment404ResponseErrorsInner',   'ListSegment200Response',   'ListSegment500Response',   'ListSegment500ResponseErrorsInner',   'SegmentSummary',   'SegmentWriteV2'  ]
# Testing code