"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Verified Senders API
  The Twilio SendGrid Verified Senders API allows you to programmatically manage the Sender Identities that are authorized to send email for your account. You can also manage Sender Identities in the [SendGrid application user interface](https://app.sendgrid.com/settings/sender_auth). See [**Single Sender Verification**](https://sendgrid.com/docs/ui/sending-email/sender-verification/) for more information.  You an use this API to create new Sender Identities, retrieve a list of existing Sender Identities, check the status of a Sender Identity, update a Sender Identity, and delete a Sender Identity.  This API offers additional operations to check for domains known to implement DMARC and resend verification emails to Sender Identities that have yet to complete the verification process.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.verified_senders.v3.models.create_verified_sender400_response import (
    CreateVerifiedSender400Response,
)
from sendgrid.rest.api.verified_senders.v3.models.create_verified_sender400_response_errors_inner import (
    CreateVerifiedSender400ResponseErrorsInner,
)
from sendgrid.rest.api.verified_senders.v3.models.delete_verified_sender403_response import (
    DeleteVerifiedSender403Response,
)
from sendgrid.rest.api.verified_senders.v3.models.delete_verified_sender403_response_errors_inner import (
    DeleteVerifiedSender403ResponseErrorsInner,
)
from sendgrid.rest.api.verified_senders.v3.models.delete_verified_sender404_response import (
    DeleteVerifiedSender404Response,
)
from sendgrid.rest.api.verified_senders.v3.models.error_response import ErrorResponse
from sendgrid.rest.api.verified_senders.v3.models.error_response_errors_inner import (
    ErrorResponseErrorsInner,
)
from sendgrid.rest.api.verified_senders.v3.models.list_verified_sender200_response import (
    ListVerifiedSender200Response,
)
from sendgrid.rest.api.verified_senders.v3.models.list_verified_sender_domain200_response import (
    ListVerifiedSenderDomain200Response,
)
from sendgrid.rest.api.verified_senders.v3.models.list_verified_sender_domain200_response_results import (
    ListVerifiedSenderDomain200ResponseResults,
)
from sendgrid.rest.api.verified_senders.v3.models.list_verified_sender_steps_completed200_response import (
    ListVerifiedSenderStepsCompleted200Response,
)
from sendgrid.rest.api.verified_senders.v3.models.list_verified_sender_steps_completed200_response_results import (
    ListVerifiedSenderStepsCompleted200ResponseResults,
)
from sendgrid.rest.api.verified_senders.v3.models.verified_sender_request import (
    VerifiedSenderRequest,
)
from sendgrid.rest.api.verified_senders.v3.models.verified_sender_response import (
    VerifiedSenderResponse,
)

__all__ = [
    "CreateVerifiedSender400Response",
    "CreateVerifiedSender400ResponseErrorsInner",
    "DeleteVerifiedSender403Response",
    "DeleteVerifiedSender403ResponseErrorsInner",
    "DeleteVerifiedSender404Response",
    "ErrorResponse",
    "ErrorResponseErrorsInner",
    "ListVerifiedSender200Response",
    "ListVerifiedSenderDomain200Response",
    "ListVerifiedSenderDomain200ResponseResults",
    "ListVerifiedSenderStepsCompleted200Response",
    "ListVerifiedSenderStepsCompleted200ResponseResults",
    "VerifiedSenderRequest",
    "VerifiedSenderResponse",
]
# Testing code
