"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Custom Fields API
  The Twilio SendGrid Marketing Campaigns Custom Fields API allows you to add extra information about your marketing contacts that is relevant to your needs. For example, a fashion retailer might create a custom field for customers' shoe sizes, an ice cream shop might store customers' favorite flavors in a custom field, and you can create custom fields that make sense for your business.  With custom fields, you can also create [segments](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) based on custom fields values. Your custom fields are completely customizable to the use-cases and user information that you need.  You can also manage your Custom Fields using the SendGrid application user interface. See [**Using Custom Fields**](https://docs.sendgrid.com/ui/managing-contacts/custom-fields) for more information, including a list of Reserved Fields. You can also manage your custom fields in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/custom-fields).
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.mc_custom_fields.v3.models.create_field_definition200_response import (
    CreateFieldDefinition200Response,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.create_field_definition400_response import (
    CreateFieldDefinition400Response,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.create_field_definition_request import (
    CreateFieldDefinitionRequest,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.custom_field_definitions_response import (
    CustomFieldDefinitionsResponse,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.custom_fields_error import (
    CustomFieldsError,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.field_type import FieldType
from sendgrid.rest.api.mc_custom_fields.v3.models.field_type1 import FieldType1
from sendgrid.rest.api.mc_custom_fields.v3.models.field_type2 import FieldType2
from sendgrid.rest.api.mc_custom_fields.v3.models.list_field_definition200_response import (
    ListFieldDefinition200Response,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.metadata import Metadata
from sendgrid.rest.api.mc_custom_fields.v3.models.reserved_field_definitions_response_inner import (
    ReservedFieldDefinitionsResponseInner,
)
from sendgrid.rest.api.mc_custom_fields.v3.models.update_field_definition_request import (
    UpdateFieldDefinitionRequest,
)

__all__ = [
    "CreateFieldDefinition200Response",
    "CreateFieldDefinition400Response",
    "CreateFieldDefinitionRequest",
    "CustomFieldDefinitionsResponse",
    "CustomFieldsError",
    "FieldType",
    "FieldType1",
    "FieldType2",
    "ListFieldDefinition200Response",
    "Metadata",
    "ReservedFieldDefinitionsResponseInner",
    "UpdateFieldDefinitionRequest",
]
# Testing code
