"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Statistics API
  The Twilio SendGrid Statistics API allows you to retrieve the various statistics related to your email program.  Tracking your emails is an important part of being a good sender and learning about how your users interact with your email. This includes everything from clicks and opens to looking at which browsers and mailbox providers your customers use.  SendGrid has broken up statistics in specific ways so that you can get at-a-glance data, as well as the details of how your email is being used.  Category statistics are available for the previous thirteen months only.  See [**Statistics Overview**](https://docs.sendgrid.com/ui/analytics-and-reporting/stats-overview) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.stats.v3.models.advanced_stats_clicks import AdvancedStatsClicks
from sendgrid.rest.api.stats.v3.models.advanced_stats_clicks_opens import (
    AdvancedStatsClicksOpens,
)
from sendgrid.rest.api.stats.v3.models.advanced_stats_mailbox_provider import (
    AdvancedStatsMailboxProvider,
)
from sendgrid.rest.api.stats.v3.models.advanced_stats_opens import AdvancedStatsOpens
from sendgrid.rest.api.stats.v3.models.aggregated_by import AggregatedBy
from sendgrid.rest.api.stats.v3.models.aggregated_by1 import AggregatedBy1
from sendgrid.rest.api.stats.v3.models.aggregated_by2 import AggregatedBy2
from sendgrid.rest.api.stats.v3.models.aggregated_by3 import AggregatedBy3
from sendgrid.rest.api.stats.v3.models.category_stats import CategoryStats
from sendgrid.rest.api.stats.v3.models.category_stats_stats_inner import (
    CategoryStatsStatsInner,
)
from sendgrid.rest.api.stats.v3.models.category_stats_stats_inner_metrics import (
    CategoryStatsStatsInnerMetrics,
)
from sendgrid.rest.api.stats.v3.models.client_type import ClientType
from sendgrid.rest.api.stats.v3.models.country import Country
from sendgrid.rest.api.stats.v3.models.list_browser_stat200_response_inner import (
    ListBrowserStat200ResponseInner,
)
from sendgrid.rest.api.stats.v3.models.list_browser_stat200_response_inner_stats_inner import (
    ListBrowserStat200ResponseInnerStatsInner,
)
from sendgrid.rest.api.stats.v3.models.list_category200_response_inner import (
    ListCategory200ResponseInner,
)
from sendgrid.rest.api.stats.v3.models.list_category400_response import (
    ListCategory400Response,
)
from sendgrid.rest.api.stats.v3.models.list_category400_response_errors_inner import (
    ListCategory400ResponseErrorsInner,
)
from sendgrid.rest.api.stats.v3.models.list_client_stat200_response_inner import (
    ListClientStat200ResponseInner,
)
from sendgrid.rest.api.stats.v3.models.list_client_stat200_response_inner_stats_inner import (
    ListClientStat200ResponseInnerStatsInner,
)
from sendgrid.rest.api.stats.v3.models.list_geo_stat200_response_inner import (
    ListGeoStat200ResponseInner,
)
from sendgrid.rest.api.stats.v3.models.list_geo_stat200_response_inner_stats_inner import (
    ListGeoStat200ResponseInnerStatsInner,
)
from sendgrid.rest.api.stats.v3.models.list_mailbox_provider_stat200_response_inner import (
    ListMailboxProviderStat200ResponseInner,
)
from sendgrid.rest.api.stats.v3.models.list_mailbox_provider_stat200_response_inner_stats_inner import (
    ListMailboxProviderStat200ResponseInnerStatsInner,
)
from sendgrid.rest.api.stats.v3.models.list_stat200_response_inner import (
    ListStat200ResponseInner,
)
from sendgrid.rest.api.stats.v3.models.list_stat200_response_inner_stats_inner import (
    ListStat200ResponseInnerStatsInner,
)
from sendgrid.rest.api.stats.v3.models.sort_by_direction import SortByDirection
from sendgrid.rest.api.stats.v3.models.stats_advanced_global_stats import (
    StatsAdvancedGlobalStats,
)

__all__ = [
    "AdvancedStatsClicks",
    "AdvancedStatsClicksOpens",
    "AdvancedStatsMailboxProvider",
    "AdvancedStatsOpens",
    "AggregatedBy",
    "AggregatedBy1",
    "AggregatedBy2",
    "AggregatedBy3",
    "CategoryStats",
    "CategoryStatsStatsInner",
    "CategoryStatsStatsInnerMetrics",
    "ClientType",
    "Country",
    "ListBrowserStat200ResponseInner",
    "ListBrowserStat200ResponseInnerStatsInner",
    "ListCategory200ResponseInner",
    "ListCategory400Response",
    "ListCategory400ResponseErrorsInner",
    "ListClientStat200ResponseInner",
    "ListClientStat200ResponseInnerStatsInner",
    "ListGeoStat200ResponseInner",
    "ListGeoStat200ResponseInnerStatsInner",
    "ListMailboxProviderStat200ResponseInner",
    "ListMailboxProviderStat200ResponseInnerStatsInner",
    "ListStat200ResponseInner",
    "ListStat200ResponseInnerStatsInner",
    "SortByDirection",
    "StatsAdvancedGlobalStats",
]
# Testing code
