"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Recipients' Data Erasure API
  The Recipients' Data Erasure API allows Twilio SendGrid customers to delete their own customers' personal data from the Twilio SendGrid Platform. The use of this API facilitates the self-service removal of email personal data from the Twilio SendGrid platform and will enable customers to comply with various obligatory data privacy regulations.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""

# import models into model package
from sendgrid.rest.api.recipients_data_erasure.v3.models.recipients_data_erasure_erase_recipients_request import (
    RecipientsDataErasureEraseRecipientsRequest,
)
from sendgrid.rest.api.recipients_data_erasure.v3.models.recipients_data_erasure_error_v1 import (
    RecipientsDataErasureErrorV1,
)
from sendgrid.rest.api.recipients_data_erasure.v3.models.recipients_data_erasure_job_id import (
    RecipientsDataErasureJobId,
)

__all__ = [
    "RecipientsDataErasureEraseRecipientsRequest",
    "RecipientsDataErasureErrorV1",
    "RecipientsDataErasureJobId",
]
# Testing code
