"""
  This code was generated by
 
  SENDGRID-OAI-GENERATOR
 
  Twilio SendGrid Marketing Campaigns Single Sends API
  The Twilio SendGrid Single Sends API allows you to create, manage, and send Single Sends. You can also search Single Sends and retrieve statistics about them to help you maintain, alter, and further develop your campaigns.  A Single Send is a one-time non-automated email message delivered to a list or segment of your audience. A Single Send may be sent immediately or scheduled for future delivery.  Single Sends can serve many use cases, including promotional offers, engagement campaigns, newsletters, announcements, legal notices, or policy updates. You can also create and manage Single Sends in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/single-sends).  The Single Sends API changed on May 6, 2020. See [**Single Sends 2020 Update**](https://docs.sendgrid.com/for-developers/sending-email/single-sends-2020-update) for more information.
 
  NOTE: This class is auto generated by OpenAPI Generator.
  https://openapi-generator.tech
  Do not edit the class manually.
"""


# import models into model package
from sendgrid.rest.api.mc_singlesends.v3.models.ab_test_summary import AbTestSummary
from sendgrid.rest.api.mc_singlesends.v3.models.duplicate_single_send_request import DuplicateSingleSendRequest
from sendgrid.rest.api.mc_singlesends.v3.models.editor import Editor
from sendgrid.rest.api.mc_singlesends.v3.models.editor1 import Editor1
from sendgrid.rest.api.mc_singlesends.v3.models.items import Items
from sendgrid.rest.api.mc_singlesends.v3.models.list_category200_response import ListCategory200Response
from sendgrid.rest.api.mc_singlesends.v3.models.list_single_send200_response import ListSingleSend200Response
from sendgrid.rest.api.mc_singlesends.v3.models.list_single_send500_response import ListSingleSend500Response
from sendgrid.rest.api.mc_singlesends.v3.models.list_single_send500_response_errors_inner import ListSingleSend500ResponseErrorsInner
from sendgrid.rest.api.mc_singlesends.v3.models.metadata import Metadata
from sendgrid.rest.api.mc_singlesends.v3.models.schedule_single_send201_response import ScheduleSingleSend201Response
from sendgrid.rest.api.mc_singlesends.v3.models.schedule_single_send_request import ScheduleSingleSendRequest
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_request import SinglesendRequest
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_request_email_config import SinglesendRequestEmailConfig
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_request_send_to import SinglesendRequestSendTo
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_response import SinglesendResponse
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_response_email_config import SinglesendResponseEmailConfig
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_response_send_to import SinglesendResponseSendTo
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_response_short import SinglesendResponseShort
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_response_warnings_inner import SinglesendResponseWarningsInner
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_schedule import SinglesendSchedule
from sendgrid.rest.api.mc_singlesends.v3.models.singlesend_search import SinglesendSearch
from sendgrid.rest.api.mc_singlesends.v3.models.status import Status
from sendgrid.rest.api.mc_singlesends.v3.models.status1 import Status1
from sendgrid.rest.api.mc_singlesends.v3.models.status2 import Status2
from sendgrid.rest.api.mc_singlesends.v3.models.status3 import Status3
from sendgrid.rest.api.mc_singlesends.v3.models.type import Type
from sendgrid.rest.api.mc_singlesends.v3.models.winner_criteria import WinnerCriteria
__all__ = [ 'AbTestSummary',   'DuplicateSingleSendRequest',   'Editor',   'Editor1',   'Items',   'ListCategory200Response',   'ListSingleSend200Response',   'ListSingleSend500Response',   'ListSingleSend500ResponseErrorsInner',   'Metadata',   'ScheduleSingleSend201Response',   'ScheduleSingleSendRequest',   'SinglesendRequest',   'SinglesendRequestEmailConfig',   'SinglesendRequestSendTo',   'SinglesendResponse',   'SinglesendResponseEmailConfig',   'SinglesendResponseSendTo',   'SinglesendResponseShort',   'SinglesendResponseWarningsInner',   'SinglesendSchedule',   'SinglesendSearch',   'Status',   'Status1',   'Status2',   'Status3',   'Type',   'WinnerCriteria'  ]
# Testing code