# https://beta.ruff.rs
name: ruff
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --user ruff
      - run: ruff --ignore="E722,F40,F841" --line-length=320 --target-version=py37 .
